### ISSUE TITLE
PerpindicularPaths - Game Timer

### ISSUE THREAD

**Issue by 8888** [Jagermeister/PerpendicularPaths#21]
The game timer is inaccurate when a level is completed.
![screen shot 2015-05-14 at 11 29 41 pm](https://cloud.githubusercontent.com/assets/12192248/7646412/3aa5c998-fa91-11e4-9290-27510a21a82d.png)

**Comment by 8888** [comment]
![screen shot 2015-05-14 at 11 39 39 pm](https://cloud.githubusercontent.com/assets/12192248/7646514/94faae1c-fa92-11e4-9a3f-aa19bb9c59fe.png)

**Comment by Jagermeister** [comment]
http://stackoverflow.com/questions/17498199/why-are-there-differences-in-python-time-time-and-time-clock-on-mac-os-x

**Comment by Jagermeister** [comment]
19cb4d8e1320aa7f5d9e4dd1865fba346e4472a9
