### ISSUE TITLE
feat/board-from-json - Entering an incorrect value for Key

### ISSUE THREAD

**Issue by 8888** [Jagermeister/PerpendicularPaths#27]
If you enter the key incorrectly the program crashes.

![screen shot 2015-05-19 at 9 47 19 am](https://cloud.githubusercontent.com/assets/12192248/7704404/19673478-fe0c-11e4-9f4a-9c27812d45e5.png)

**Comment by Jagermeister** [comment]
9c5271de401373b0c5487a1480bd4d6ca39f09cd
