### ISSUE TITLE
Blocked Solution

### ISSUE THREAD

**Issue by 8888** [Jagermeister/PerpendicularPaths#36]
The solution generator creates a solution that can block itself by placing a non-goal piece on the goal. The following parameters were noticed:

-A non-goal piece is lined up with the goal on the optimal space that the goal piece needs to move onto to then move to the goal.
-The only move for the non-goal piece that doesn't obstruct the goal piece's desired path is onto the goal
-Once the goal piece is moved onto the optimal space, the solution generator believes the puzzle is solved, but the non-goal piece is still obstructing the goal.

A check needs to be made to ensure that the goal piece is lined up with the goal and the goal is not occupied.

**Comment by 8888** [comment]
This same issue is caused if there is a piece in the way, but the goal piece is lined up with the goal.

**Comment by 8888** [comment]
Non-goal piece on the goal:
![screen shot 2016-04-08 at 9 33 43 pm](https://cloud.githubusercontent.com/assets/12192248/14401023/9dd51336-fdd1-11e5-981c-6dba858becc4.png)

Non-goal piece blocking the path to the goal:
![screen shot 2016-04-08 at 9 29 43 pm](https://cloud.githubusercontent.com/assets/12192248/14401006/2a97d1c4-fdd1-11e5-903b-a4aeac023f1a.png)

Note: The solution generator was ran after the moves were made for both of these examples. This can occur naturally without player intervention from a freshly started game.

**Comment by betterin30days** [comment]
![screen shot 2016-04-14 at 7 25 32 pm](https://cloud.githubusercontent.com/assets/12192248/14546917/c1cd03e4-0276-11e6-9d98-bfe486763686.png)

**Comment by 8888** [comment]
![screen shot 2016-04-14 at 7 25 32 pm](https://cloud.githubusercontent.com/assets/12192248/14546928/dcddae40-0276-11e6-9910-266031ee73df.png)

**Comment by 8888** [comment]
Solution solved under SolutionGeneratorFix branch
