### ISSUE TITLE
PerpindicularPaths - Must ricochet to win level

### ISSUE THREAD

**Issue by 8888** [Jagermeister/PerpendicularPaths#9]
We need to implement the rule were you must ricochet at least once before reaching the goal.
![screen shot 2015-05-11 at 12 24 26 am](https://cloud.githubusercontent.com/assets/12192248/7558566/44c3291c-f775-11e4-85a3-136d9ec8d1c6.png)

**Comment by Jagermeister** [comment]
3447348feb864755f0c690d6dd89b01ab8ff93d5
